version: "3"
services: 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    restart: unless-stopped
  alertmanager:
    image: quay.io/prometheus/alertmanager
    volumes:
      - ./alertmanager:/config
    ports:
      - '9093:9093'
    command: --config.file=/config/alertmanager.yml --log.level=debug
    
    container_name: alertmanager
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge